<org.uberfire.java.nio.base.Properties serialization="custom">
  <unserializable-parents/>
  <map>
    <default>
      <loadFactor>0.75</loadFactor>
      <threshold>12</threshold>
    </default>
    <int>16</int>
    <int>2</int>
    <string>dcore.description[0]</string>
    <string>Es una prueba de descripción</string>
    <string>othermeta.tag[0]</string>
    <string>Catalogacion</string>
  </map>
</org.uberfire.java.nio.base.Properties>