package pocuo.pocproject;

import java.lang.Number;
no-loop true

rule "CB000201"
	dialect "mvel"
	when
		$pIn:pocuo.pocproject.pocIncome( ( seg_comercial == "02P2" || seg_comercial == "02P3" || seg_comercial == "02P1" || seg_comercial == "02P4" || seg_comercial == "02P9" ),tipo_pers == "F" , cod_agrupacion == "A536" )
	then
        modify($pIn){setId_cartera( "000201" ),setCod_tipologia(drools.getRule().getName())};
	    System.out.println(drools.getRule().getName()); 
end

rule "CB000204"
	dialect "mvel"
	when
		$pIn:pocuo.pocproject.pocIncome( ( seg_comercial == "02P2" || seg_comercial == "02P3" || seg_comercial == "02P1" || seg_comercial == "02P4" || seg_comercial == "02P9" ),tipo_pers == "F" , cod_agrupacion == "A492",tipo_RNR =="1" )
	then
        modify($pIn){setId_cartera( "000204" ),setCod_tipologia(drools.getRule().getName())};
	    System.out.println(drools.getRule().getName()); 
end
