package pocuo.pocproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Modelo de datos PoC")
@org.kie.api.definition.type.Description("Entidad recoge los datos de las transferencias financieras")
public class pocIncome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PCINCOME_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PCINCOME_ID_SEQ", name = "PCINCOME_ID_GENERATOR")
   @org.kie.api.definition.type.Label("Identificador entidad")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Codigo agrupacion")
   private java.lang.String cod_agrupacion;

   @org.kie.api.definition.type.Label("Tipo RNR")
   private java.lang.String tipo_RNR;

   @org.kie.api.definition.type.Label("Tipo persona")
   private java.lang.String tipo_pers;

   @org.kie.api.definition.type.Label("Tipo producto")
   private java.lang.String tipo_prod;

   @org.kie.api.definition.type.Label("Identificador contrato")
   private java.lang.String id_contrato;

   @org.kie.api.definition.type.Label("Codigo tipologia")
   private java.lang.String cod_tipologia;

   @org.kie.api.definition.type.Label("Segmento comercial")
   private java.lang.String seg_comercial;

   @org.kie.api.definition.type.Label("Id cartera")
   private java.lang.String id_cartera;

   public pocIncome()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCod_agrupacion()
   {
      return this.cod_agrupacion;
   }

   public void setCod_agrupacion(java.lang.String cod_agrupacion)
   {
      this.cod_agrupacion = cod_agrupacion;
   }

   public java.lang.String getTipo_RNR()
   {
      return this.tipo_RNR;
   }

   public void setTipo_RNR(java.lang.String tipo_RNR)
   {
      this.tipo_RNR = tipo_RNR;
   }

   public java.lang.String getTipo_pers()
   {
      return this.tipo_pers;
   }

   public void setTipo_pers(java.lang.String tipo_pers)
   {
      this.tipo_pers = tipo_pers;
   }

   public java.lang.String getTipo_prod()
   {
      return this.tipo_prod;
   }

   public void setTipo_prod(java.lang.String tipo_prod)
   {
      this.tipo_prod = tipo_prod;
   }

   public java.lang.String getId_contrato()
   {
      return this.id_contrato;
   }

   public void setId_contrato(java.lang.String id_contrato)
   {
      this.id_contrato = id_contrato;
   }

   public java.lang.String getCod_tipologia()
   {
      return this.cod_tipologia;
   }

   public void setCod_tipologia(java.lang.String cod_tipologia)
   {
      this.cod_tipologia = cod_tipologia;
   }

   public java.lang.String getSeg_comercial()
   {
      return this.seg_comercial;
   }

   public void setSeg_comercial(java.lang.String seg_comercial)
   {
      this.seg_comercial = seg_comercial;
   }

   public java.lang.String getId_cartera()
   {
      return this.id_cartera;
   }

   public void setId_cartera(java.lang.String id_cartera)
   {
      this.id_cartera = id_cartera;
   }

   public pocIncome(java.lang.Long id, java.lang.String cod_agrupacion,
         java.lang.String tipo_RNR, java.lang.String tipo_pers,
         java.lang.String tipo_prod, java.lang.String id_contrato,
         java.lang.String cod_tipologia, java.lang.String seg_comercial,
         java.lang.String id_cartera)
   {
      this.id = id;
      this.cod_agrupacion = cod_agrupacion;
      this.tipo_RNR = tipo_RNR;
      this.tipo_pers = tipo_pers;
      this.tipo_prod = tipo_prod;
      this.id_contrato = id_contrato;
      this.cod_tipologia = cod_tipologia;
      this.seg_comercial = seg_comercial;
      this.id_cartera = id_cartera;
   }

}