package pocuo.pocproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pocOutcome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "POCOUTCOME_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "POCOUTCOME_ID_SEQ", name = "POCOUTCOME_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Identificador cartera")
   private java.lang.String id_cartera;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("Transactions")
   private java.util.List<pocuo.pocproject.pocIncome> transactionsList;

   public pocOutcome()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getId_cartera()
   {
      return this.id_cartera;
   }

   public void setId_cartera(java.lang.String id_cartera)
   {
      this.id_cartera = id_cartera;
   }

   public java.util.List<pocuo.pocproject.pocIncome> getTransactionsList()
   {
      return this.transactionsList;
   }

   public void setTransactionsList(
         java.util.List<pocuo.pocproject.pocIncome> transactionsList)
   {
      this.transactionsList = transactionsList;
   }

   public pocOutcome(java.lang.Long id, java.lang.String id_cartera,
         java.util.List<pocuo.pocproject.pocIncome> transactionsList)
   {
      this.id = id;
      this.id_cartera = id_cartera;
      this.transactionsList = transactionsList;
   }

}