package pocuo.pocproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("PoC results")
public class pocResults implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "TimeStamp")
   private java.util.Date timestamp;
   @org.kie.api.definition.type.Label(value = "Transactions")
   private java.util.List<pocuo.pocproject.pocIncome> transactionsList;

   public pocResults()
   {
   }

   public java.util.Date getTimestamp()
   {
      return this.timestamp;
   }

   public void setTimestamp(java.util.Date timestamp)
   {
      this.timestamp = timestamp;
   }

   public java.util.List<pocuo.pocproject.pocIncome> getTransactionsList()
   {
      return this.transactionsList;
   }

   public void setTransactionsList(
         java.util.List<pocuo.pocproject.pocIncome> transactionsList)
   {
      this.transactionsList = transactionsList;
   }

   public pocResults(java.util.Date timestamp,
         java.util.List<pocuo.pocproject.pocIncome> transactionsList)
   {
      this.timestamp = timestamp;
      this.transactionsList = transactionsList;
   }

}